export const LIST_TODO = "LIST_TODO";
export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";

export const FETCH_GITHUB_USER = 'FETCH_GITHUB_USER';
export const FETCH_GITHUB_USER_SUCCESS = 'FETCH_GITHUB_USER_SUCCESS';
export const FETCH_GITHUB_USER_FAIL = 'FETCH_GITHUB_USER_FAIL';
